import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Disclosure – DreamRiver",
  description:
    "How DreamRiver uses AI to interpret dreams: what's generated, how scripture is matched, and how credits and feedback work.",
};

// New page, HANDOFF-v3.md §6 (linked from the v3 footer) — product-transparency
// copy explaining the §5 AI-transparency contract in plain language. This is
// NOT binding legal text (see app/terms/page.tsx §5 "AI-Generated Content
// Disclaimer" for that); it exists so a curious user can read, in one place,
// what "AI-generated" actually means on DreamRiver before they ever open a
// dream.
export default function AiDisclosurePage() {
  return (
    <div className="flex-1 w-full flex flex-col items-center px-4 py-12">
      <div className="max-w-2xl w-full space-y-8">
        <h1 className="text-3xl font-bold text-center">AI Disclosure</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 text-center">
          How DreamRiver uses AI, in plain language.
        </p>

        <div className="space-y-6 text-gray-600 dark:text-gray-300 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              What&apos;s AI-generated
            </h2>
            <p>
              Every dream interpretation on DreamRiver — the analysis, the
              tags, the reflection questions — is generated by a large
              language model, not written by a person and not sourced from a
              theologian or pastor. Scripture quotations themselves come from
              a fixed King James Version text, so the words of a verse are
              always accurate; the connection the reading draws between your
              dream and that verse is the model&apos;s own read of your
              entry.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              A starting point, not doctrine
            </h2>
            <p>
              Every interpretation carries this line, next to the DreamRiver
              mark, directly above the reading itself:
            </p>
            <p className="italic border-l-2 border-primary pl-4">
              &ldquo;Generated with AI and grounded in the verses below. A
              starting point for reflection — not doctrine.&rdquo;
            </p>
            <p>
              We mean that literally. Treat each reading as a prompt for your
              own reflection, prayer, or conversation with clergy — not as
              scripture, prophecy, or a substitute for pastoral or
              professional guidance. See the{" "}
              <Link href="/terms" className="text-primary underline">
                Terms of Service
              </Link>{" "}
              for the full disclaimer.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              How verses are matched
            </h2>
            <p>
              When you submit a dream, the model identifies the symbols and
              themes in your description and searches for scripture that
              speaks to them. Each verse citation is shown together with the
              theme it was matched on — for example{" "}
              <span className="whitespace-nowrap">
                &ldquo;Isaiah 43:2 · crossing waters&rdquo;
              </span>{" "}
              — so you can see why a verse was chosen, not only that it was.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              Credits, shown before you spend them
            </h2>
            <p>
              DreamRiver&apos;s free tier includes a limited number of
              interpretations. Whenever a reading is about to cost a credit —
              including re-running an existing interpretation — the cost is
              shown on the same screen as the button, before you tap it. We
              never deduct a credit and disclose the cost afterward.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              Re-reading a dream
            </h2>
            <p>
              A first reading doesn&apos;t always land the way you expect,
              and dreams can read differently on different days. You can
              re-run the interpretation for any saved dream with &ldquo;Read
              again&rdquo;; each re-run costs the same credit as a fresh
              interpretation, and that cost is always stated on the button
              itself.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              Your feedback shapes the model
            </h2>
            <p>
              After each reading, we ask one question: &ldquo;Did this
              reading feel meaningful?&rdquo; Your answer is saved to that
              dream entry and used only to understand whether our
              interpretations are actually helpful — it is never sold and
              never used to profile you elsewhere. It is the main signal we
              use to improve prompts and verse-matching over time.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              Reading level
            </h2>
            <p>
              We aim for interpretations that are clear and direct — roughly
              an 8th-grade reading level at our &ldquo;Still Waters&rdquo;
              and &ldquo;Flowing River&rdquo; depths — because a dream
              interpretation you have to decode isn&apos;t much of a
              reflection aid.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              Where your data goes
            </h2>
            <p>
              Your dream text is sent to OpenAI to generate the analysis, and
              is never used to train their models. See the{" "}
              <Link href="/privacy" className="text-primary underline">
                Privacy Policy
              </Link>{" "}
              for the full list of processors and what each one sees.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              Questions
            </h2>
            <p>
              If anything here is unclear, or you&apos;d like to know more
              about how a specific reading was produced,{" "}
              <Link href="/contact" className="text-primary underline">
                contact us
              </Link>
              .
            </p>
          </section>
        </div>

        <div className="pt-4 text-center">
          <Link
            href="/"
            className="text-sm text-gray-500 dark:text-gray-400 hover:underline"
          >
            &larr; Back to journal
          </Link>
        </div>
      </div>
    </div>
  );
}
