'use client';

import { useRef, useState } from 'react';
import WYSIWYGReportPreview from './wysiwyg-report-preview';
import type { WYSIWYGPreviewHandle } from './wysiwyg-report-preview';
import type { ExportReportData, ChangeProposal } from '@/lib/types/report-export';

interface ReportPageClientProps {
  reportData: ExportReportData;
}

/**
 * Client wrapper for the report preview page.
 * Holds a ref to the preview so we can call proposeChanges() externally
 * (e.g., from AI re-analysis, data imports, or the demo button).
 */
export default function ReportPageClient({ reportData }: ReportPageClientProps) {
  const previewRef = useRef<WYSIWYGPreviewHandle>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  /**
   * Triggers an AI re-analysis for this dream report.
   * Shows processing indicator, calls the API, then flags affected cards.
   */
  const handleReanalyze = async () => {
    if (!previewRef.current || isSubmitting) return;
    setIsSubmitting(true);

    // Show processing state on the preview
    previewRef.current.setProcessing(true, 'Re-analyzing with AI\u2026');

    try {
      // Simulate an AI analysis call (replace with real API call later)
      // In production this would be: const res = await fetch('/api/openai-analysis', { ... })
      await new Promise((resolve) => setTimeout(resolve, 2500));

      // Build proposals from the "AI response"
      const proposals: ChangeProposal[] = reportData.sections
        .filter((_, i) => i % 2 === 0) // demo: flag every other section
        .map((section) => ({
          sectionId: section.id,
          proposedContent: section.content
            ? section.content + ' [Updated with deeper spiritual insight from re-analysis.]'
            : 'New content generated by AI re-analysis.',
          reason: 'AI re-analysis',
          timestamp: Date.now(),
        }));

      // Hide processing, then flag the cards
      previewRef.current.setProcessing(false);
      previewRef.current.proposeChanges(proposals);
    } catch {
      previewRef.current.setProcessing(false);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      {/* Toolbar */}
      <div className="max-w-6xl mx-auto px-4 pt-4 flex justify-end">
        <button
          onClick={handleReanalyze}
          disabled={isSubmitting}
          className={`
            inline-flex items-center gap-2 text-xs font-medium px-3 py-1.5 rounded-md border transition-colors
            ${isSubmitting
              ? 'border-gray-200 bg-gray-50 text-gray-400 cursor-not-allowed'
              : 'border-amber-300 bg-amber-50 text-amber-800 hover:bg-amber-100'
            }
          `}
        >
          {isSubmitting ? (
            <>
              <svg
                className="animate-spin"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
              >
                <path d="M21 12a9 9 0 1 1-6.219-8.56" />
              </svg>
              Analyzing\u2026
            </>
          ) : (
            <>
              <svg
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
                <path d="M3 3v5h5" />
                <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
                <path d="M16 16h5v5" />
              </svg>
              Re-analyze with AI
            </>
          )}
        </button>
      </div>

      <WYSIWYGReportPreview ref={previewRef} initialData={reportData} />
    </>
  );
}
