import { z } from "zod";

export const chatGptSchema = z.object({
  id: z.string().uuid().optional(), // Optional on creation; generated by DB
  dream_entry_id: z.string().uuid(),  // Foreign key linking to a dream entry
  prompt: z.string(),                 // The prompt text sent to ChatGPT
  response: z.string(),               // The response received from ChatGPT
  model: z.string().optional(),       // The model used (e.g., "gpt-3.5-turbo")
  temperature: z.number().optional(), // Temperature setting for generation
  created_at: z.string().optional(),  // Timestamp (ISO string) when created
});

export type ChatGpt = z.infer<typeof chatGptSchema>;